on:
  schedule: [{cron: "*/15 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Latest Tweet
        uses: lowlighter/metrics@latest
        with:
          filename: tweets.svg
          token: NOT_NEEDED
          base: ""
          plugin_tweets_token: ${{ secrets.TWITTER }}
          plugin_tweets_user: aeristhy
          plugin_tweets: yes
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 2
