on:
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_achievements_display: compact
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0  
