on:
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Latest Tweet
        uses: lowlighter/metrics@latest
        with:
          filename: tweets.svg
          token: ${{ secrets.TWITTER_TOKEN }}
          base: ""
          plugin_tweets_user: github
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 2
