on:
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: tweets.svg
          token: ${{ secrets.TWITTER_TOKEN }}
          base: ""
          plugin_tweets: yes
